TL 98
Train-lab-intern/backend_dev pull request #11
Opened 2023-08-11 10:53 UTC by Petrovich-A

…ciated with transformation into json, replaced nanoseconds in Timestamp

2023-08-11 11:28 UTC, nikita-pohodski requested changes

2023-08-11 11:28 UTC, nikita-pohodski commented on api/src/main/java/com/trainlab/controller/RoleApi.java
> +public interface RoleApi {
```suggestion
public interface RoleController {
```

2023-08-11 11:28 UTC, nikita-pohodski commented on api/src/main/java/com/trainlab/controller/RoleApi.java
> +                            description = "Creating a new role",
```suggestion
                            description = "Created a new role",
```

2023-08-11 11:28 UTC, nikita-pohodski commented on api/src/main/java/com/trainlab/controller/RoleApi.java
> +    @PutMapping("/{id}")
Можно убрать из интерфейса, т.к. эти аннотации остаются в имплементации

2023-08-11 11:28 UTC, nikita-pohodski commented on api/src/main/java/com/trainlab/controller/RoleApi.java
> +    @GetMapping("/")
Можно убрать из интерфейса, т.к. эти аннотации остаются в имплементации

2023-08-11 11:28 UTC, nikita-pohodski commented on api/src/main/java/com/trainlab/controller/RoleApi.java
> +    @GetMapping("/{id}")
Можно убрать из интерфейса, т.к. эти аннотации остаются в имплементации

2023-08-11 11:28 UTC, nikita-pohodski commented on api/src/main/java/com/trainlab/controller/RoleApi.java
> +    @GetMapping
Можно убрать из интерфейса, т.к. эти аннотации остаются в имплементации

2023-08-11 11:28 UTC, nikita-pohodski commented on api/src/main/java/com/trainlab/controller/RoleApi.java
> +    ResponseEntity<RoleDto> createRole(@Valid @RequestBody @Parameter(description = "Role data", required = true) RoleCreateDto roleCreateDto);
```suggestion
    ResponseEntity<RoleDto> createRole(RoleCreateDto roleCreateDto);
```

2023-08-11 11:28 UTC, nikita-pohodski commented on api/src/main/java/com/trainlab/controller/RoleApi.java
> +    ResponseEntity<RoleDto> findRoleById(@PathVariable Integer id);
```suggestion
    ResponseEntity<RoleDto> findRoleById(Integer id);
```

2023-08-11 11:28 UTC, nikita-pohodski commented on api/src/main/java/com/trainlab/controller/RoleApi.java
> +    ResponseEntity<RoleDto> findRoleByRoleName(@RequestBody String roleName);
```suggestion
    ResponseEntity<RoleDto> findRoleByRoleName(String roleName);
```

2023-08-11 11:28 UTC, nikita-pohodski commented on api/src/main/java/com/trainlab/controller/RoleApi.java
> +    ResponseEntity<RoleDto> updateRole(@PathVariable("id") Integer id, @Valid @RequestBody RoleDto roleDto);
```suggestion
    ResponseEntity<RoleDto> updateRole(RoleDto roleDto);
```

2023-08-11 11:28 UTC, nikita-pohodski commented on api/src/main/java/com/trainlab/controller/RoleController.java
> +public class RoleController implements RoleApi {
```suggestion
public class RoleControllerImpl implements RoleApi {
```

2023-08-11 11:28 UTC, nikita-pohodski commented on common/src/main/java/com/trainlab/dto/RoleCreateDto.java
> +    private boolean isDeleted = false;
Убрать лишние поля isDeleted, created, changed
Не уверен что при создании клиент будет указывать удаленная роль или нет, время создания и время обновления
Это все зона ответственности бэкенда

Поэтому при создании остается только roleName

2023-08-11 11:28 UTC, nikita-pohodski commented on common/src/main/java/com/trainlab/dto/RoleDto.java
> +public class RoleDto {
Этот класс больше похож на RoleCreateDto либо на RoleUpdateDto

2023-08-11 11:28 UTC, nikita-pohodski commented on common/src/main/java/com/trainlab/dto/RoleDto.java
> +public class RoleDto {
В RoleDto нужно указать roleName, created, updated
isDeleted лишнее, т.к. если роль удалена то и отображаться не должна

2023-08-11 12:00 UTC, Petrovich-A commented on api/src/main/java/com/trainlab/controller/RoleApi.java
> +public interface RoleApi {
куда выносить? импл делать? одинаковое название нельзя для 2х файлов

2023-08-11 15:16 UTC, SvetaPiven approved these changes

2023-08-11 15:16 UTC, SvetaPiven commented on api/src/main/java/com/trainlab/controller/RoleApi.java
> +public interface RoleApi {
Мне кажется можно добавить еще тег
по типу
@Tag(name = "RoleController", description = "Rolemanagement methods")

2023-08-11 15:16 UTC, SvetaPiven commented on api/src/main/java/com/trainlab/controller/RoleApi.java
> +public interface RoleApi {
посмотри как в 97 ветке

2023-08-11 15:18 UTC, merged

2023-08-14 07:05 UTC, nikita-pohodski commented on common/src/main/java/com/trainlab/dto/RoleDto.java
> +public class RoleDto {
Так же обязательно возвращаем ID сущности в ДТО