TL-93
Train-lab-intern/backend_dev pull request #14
Opened 2023-08-14 10:22 UTC by Petrovich-A

изменил апдейт в юзер контроллере, поменял маппер, добавил тест на маппер

2023-08-14 10:29 UTC, nikita-pohodski requested changes

2023-08-14 10:29 UTC, nikita-pohodski commented on api/src/main/java/com/trainlab/controller/UserControllerImpl.java
> +        UserDto userDto = userMapper.toDto(userService.update(userUpdateDto, id, userDetails));
Перенести маппинг в сервис

2023-08-14 10:29 UTC, nikita-pohodski commented on common/src/main/java/com/trainlab/dto/UserDto.java
> +    private boolean active;
Добавить swagger описание всех полей
Вместо примитивов желательно использовать обертки

2023-08-14 10:32 UTC, Petrovich-A commented on api/src/main/java/com/trainlab/controller/UserControllerImpl.java
> +        UserDto userDto = userMapper.toDto(userService.update(userUpdateDto, id, userDetails));
в юзер контроллере везде нужно

2023-08-14 10:32 UTC, Petrovich-A commented on common/src/main/java/com/trainlab/dto/UserDto.java
> +    private boolean active;
давай пока мерж, потом может света поменяет, не хочу влазить. или как?

2023-08-14 10:53 UTC, nikita-pohodski commented on api/src/main/java/com/trainlab/controller/UserControllerImpl.java
> +        UserDto userDto = userMapper.toDto(userService.update(userUpdateDto, id, userDetails));
Почему? Мы же договорились что мапперы будут в сервисах

2023-08-14 10:54 UTC, nikita-pohodski commented on common/src/main/java/com/trainlab/dto/UserDto.java
> +    private boolean active;
Конечно влазь) Какой смысл следить только за своим кодом, тем более это в рамках твоего ПР

2023-08-14 18:49 UTC, KateKoml approved these changes

2023-08-15 11:09 UTC, nikita-pohodski approved these changes

2023-08-15 11:09 UTC, nikita-pohodski commented on common/src/main/java/com/trainlab/dto/RoleDto.java
> +@Schema(description = "Role DTO data to UI role response")
UI неправильная формулировка. 
т.е. на UI отправляет данные фронт, а мы отправляем в API а куда дальше данные пойдут нам по большему счету все равно

2023-08-15 11:09 UTC, nikita-pohodski commented on common/src/main/java/com/trainlab/dto/RoleUpdateDto.java
> +    private boolean isDeleted = false;
Лучше использовать обертки вместо примитивов

2023-08-15 11:09 UTC, nikita-pohodski commented on common/src/main/java/com/trainlab/service/impl/UserServiceImpl.java
> +    }
```suggestion
    private void checkUserAuthority(User user, UserDetails userDetails) {
        String userEmail = user.getAuthenticationInfo().getEmail();
        String username = userDetails.getUsername();
        if (!userEmail.equalsIgnoreCase(username)) {
            throw new AccessDeniedException("Access denied");
        }
    }
```

2023-08-15 11:09 UTC, nikita-pohodski commented on common/src/main/java/com/trainlab/service/impl/UserServiceImpl.java
> +            userDto = userMapper.toDto(user);
```suggestion
        this.checkUserAuthority(user, userDetails);
        UserDto userDto = userMapper.toDto(user);
```

2023-08-15 12:00 UTC, Petrovich-A commented on common/src/main/java/com/trainlab/service/impl/UserServiceImpl.java
> +    }
так а почему воид? результат же нужен

2023-08-15 17:48 UTC, merged