Tl 93
Train-lab-intern/backend_dev pull request #8
Opened 2023-08-09 15:36 UTC by Petrovich-A

пробник

2023-08-10 07:13 UTC, nikita-pohodski requested changes

2023-08-10 07:13 UTC, nikita-pohodski commented on common/src/main/java/com/trainlab/model/AuthenticationInfo.java
> +@EqualsAndHashCode
```suggestion
@AllArgsConstructor
@NoArgsConstructor
@Embeddable
@Builder
@Data
```

Можно сократить несколько аннотаций

2023-08-10 07:13 UTC, nikita-pohodski commented on common/src/main/java/com/trainlab/model/Session.java
> +@EqualsAndHashCode
Можно сократить к Data

2023-08-10 07:13 UTC, nikita-pohodski commented on common/src/main/java/com/trainlab/model/User.java
> +@EqualsAndHashCode
Можно сократить к Data

2023-08-10 07:13 UTC, nikita-pohodski commented on common/src/main/java/com/trainlab/service/impl/UserServiceImpl.java
> +    private void encodePassword(User user) {
```suggestion
    private void encodePasswordAndSetToUser(User user) {
```

Вообще, есть ли смысл выносить в отдельный метод 2 строки кода только потому что они повторяются 2 раза в сервисе?

2023-08-10 07:13 UTC, nikita-pohodski commented on common/src/main/java/com/trainlab/service/impl/UserServiceImpl.java
>      }
Лучше оставить как было.
Потому что так вообще не читается. Сокращено 3 строчки, но не читабельно

setDefaultRole исправить в метод getDefaultRole  который возвращает дефолтную роль. А в методе create добавить эту роль юзеру.

Плохая практика менять состояние экземпляра класса в тех методах в которых он не создавался.

2023-08-10 07:13 UTC, nikita-pohodski commented on common/src/test/java/com/trainlab/repository/SessionRepositoryTest.java
> +                .build();
```suggestion
        User user = User.builder()
                .id(userId)
                .username("test")
                .authenticationInfo(AuthenticationInfo.builder()
                    .email("test@gmail.com")
                    .userPassword("$2a$06$dnfljySL5wwO918hOHWkwOfOzSuQMORHXAr5em7CzMREoxnCJx3UC")
                    .build())
                .created(Timestamp.valueOf("2023-07-13 16:28:08.000000"))
                .changed(Timestamp.valueOf("2023-07-31 15:32:53.462876"))
                .active(false)
                .isDeleted(false)
                .build();
```

2023-08-10 07:13 UTC, nikita-pohodski commented on common/src/test/java/com/trainlab/repository/SessionRepositoryTest.java
> +                .build();
С билдерами можно так, без создания экземпляра

2023-08-10 07:13 UTC, nikita-pohodski commented on common/src/test/java/com/trainlab/service/impl/UserServiceImplTest.java
> +//                .created(Timestamp.valueOf("2023-07-13 16:28:08.000000"))
?

2023-08-10 07:13 UTC, nikita-pohodski commented on common/src/test/java/com/trainlab/service/impl/UserServiceImplTest.java
> +//                .created(Timestamp.valueOf("2023-07-13 16:28:08.000000"))
? Почему закоменчено

2023-08-10 11:00 UTC, Petrovich-A commented on common/src/main/java/com/trainlab/model/Session.java
> +@EqualsAndHashCode
не рекомендуют...

2023-08-10 11:01 UTC, Petrovich-A commented on common/src/main/java/com/trainlab/service/impl/UserServiceImpl.java
> +    private void encodePassword(User user) {
я этим и руководствовался)

2023-08-10 11:03 UTC, Petrovich-A commented on common/src/test/java/com/trainlab/repository/SessionRepositoryTest.java
> +                .build();
тут не понял

2023-08-11 07:45 UTC, nikita-pohodski commented on common/src/main/java/com/trainlab/service/impl/UserServiceImpl.java
> +        roleRepository.findByRoleName("ROLE_USER").map(role -> user.getRoles().add(role))
На 124 строке есть получение роли из базы
Зачем еще раз запрос в БД и потом через map сетить роль

Чем прох был первый вариант с  user.getRoles().add(userRole); ?

2023-08-11 09:02 UTC, merged